
"Jalalabad Gas Transmission and Distribution System Limited": "জালালাবাদ গ্যাস টি এন্ড ডি সিস্টেম লিমিটেড",
"A company of Petrobangla": "পেট্রোবাংলার একটি কোম্পানি",
"Gas Bhaban, Mendibag, Sylhet": "গ্যাস ভবন, মেন্দিবাগ, সিলেট",
"Industrial/Captive Power/Tea Garden Category Customer Gas Connection/Load Increase Application Form": "শিল্প/ক্যাপটিভ পাওয়ার/চা বাগান শ্রেণী গ্রাহকের গ্যাস সংযোগ/লোড বৃদ্ধির আবেদন পত্র",
"Picture" : "ছবি",
"Application Receipt Date:": "আবেদনপত্র গ্রহণের তারিখঃ",
"No:": "নংঃ",
"Name of the Institution:": "শিল্প কারখানার নামঃ",
"Contact Address:": "যোগাযোগের ঠিকানাঃ",
"Factory:": "কারখানাঃ",
"Phone:": "ফোনঃ",
"Head Office:": "প্রধান কার্যালয়ঃ",
"Billing Office:": "বিল প্রেরনের ঠিকনাঃ",
"Ownership of industrial establishments:": "শিল্প প্রতিষ্ঠানের মালিকানাঃ",
"Land Ownership:": "জমির মালিকানাঃ",
"Type of Industry:": "শিল্পের ধরনঃ",
"Trade License Number:": "ট্রেড লাইসেন্স নম্বরঃ",
"Validity:": "মেয়াদঃ",
"Basic Information of Owner:": "প্রতিষ্ঠান মালিকের সংক্ষিপ্ত পরিচিতিঃ",
"Name and Name of Father/Husband": "নাম ও পিতা/স্বামীর নাম",
"Location of Institution:": "প্রতিষ্ঠানের অবস্থান সম্পর্কিত তথ্যঃ",
"Khatian": "খতিয়ান",
"Total land area": "মোট জমির পরিমান",
"acres": "একর",
"Name and address of allotting agency if allotted:": "বরাদ্দপ্রাপ্ত হইলে বরাদ্দ প্রদানকারী সংস্থার নাম ও থিকানাঃ",
"Either gas has been used previously or is being used currently in this land:": "ইতিপূর্বে (জানা থাকিলে) বর্তমানে এই জমিতে বা ইহার অংশ বিশেষে গ্যাস ব্যবহৃত হয়েছে/হচ্ছে কিনাঃ",
"Description of aboved mentioned gas connection:": "ইতিপূর্বে (জানা থাকিলে) বর্তমানে গ্যাস ব্যবহৃত হইলে উহার বিবরনঃ",
"Customer Code:": "গ্রাহক সংকেত নম্বরঃ",
"Factory or the Institution Name:": "কারখানা/প্রতিষ্ঠানের নামঃ",
"Name of Owner Agency:": "প্রতিষ্ঠানের মালিকের নামঃ",
"Connection Status:": "সংযোগটির অবস্থাঃ",
"NOC for Bill Payment:": "হালনাগাদ বিল পরিশোধের ছারপত্রঃ",
"Gas Supply Is Connected:": "কারখানার মালিক অংশীদার/চেয়ারম্যান ও অন্যান্য পরিচালকবৃন্দের নামে বর্তমানে কোন শিল্প/প্রতিষ্ঠান চালু বা বিচ্ছিন্ন অবস্থায় আছে কি-নাঃ",
"Name Customer Code of Institution:": "থাকিলে তাহার গ্রাহক সংকেত নম্বরঃ",
"Product Information:": "প্রতিষ্ঠানের উৎপাদন সম্পর্কিত তথ্যঃ",
"Annual raw material used:": "ব্যবহৃত বাৎসরিক কাঁচামালঃ",
"Serial": "ক্রম",
"Where is it sold?": "কোথায় বিক্রি হয়?",
"Local": "স্থানীয় বাজার",
"International": "আন্তরর্জাতিক বাজার",
"Production Process:": "উৎপাদন পদ্ধতিঃ",
"Production Operation Hour:": "দৈনিক শিল্প চালুর সময়কালঃ",
"Information on financial matters:": "আর্থিক বিষয় সম্পর্কিত তথ্যঃ",
"TIN No. of Institution:": "প্রতিষ্ঠানের ট্যাক্স আইডেনটিফিকেশনের নম্বরঃ (TIN)",
"VAT Registration No:": "প্রতিষ্ঠানের ভ্যাট রেজিষ্ট্রেশনের নম্বরঃ (প্রযোজ্য ক্ষেত্রে)",
"Bank Solvency Certificate:": "ব্যাংকের নাম ও শাখাঃ",
"Existing Gas Information": "লোড সম্পর্কিত তথ্যঃ",
"Gas Establishment": "গ্যাস স্থাপনা এর",
"Type of Burner": "বার্নার এর",
"Name": "নাম",
"The Manufacturer": "প্রস্তুতকারী",
"Size": "আকার",
"Production Capacity": "উৎপাদন ক্ষমতা",
"Type": "ধরণ",
"The Number": "সংখ্যা",
"Orifice": "অরিফিস",
"Load": "লোড ঘনমিটার",
"Total Load": "মোট লোড ঘনমিটার",
"Company": "কোম্পানী",
"Country": "দেশ",
"Proposed Gas Information:": "প্রস্তাবিত গ্যাস স্থাপনা/বার্নারঃ",
"Quantity of gas demanded per hour: (cubic meter)": "ঘন্টায় চাহিদাকৃত গ্যাসের পরিমানঃ (ঘনমিটার)",
"Desired pressure of gas:": "গ্যাসের কাঙ্খিত চাপঃ",
"When is increased gas demand required:": "বর্ধিত গ্যাস চাহিদা কখন থেকে প্রয়োজনঃ",
"The Year": "বৎসর",
"Demand": "চাহিদা",
"Cubic Meter": "ঘনমিটার",
"Demand": "চাহিদা",
"Signature": "স্বাক্ষর",
"Names and Specimen Signatures of Persons Authorized to Perform/Communicate with the Company:": "কোম্পানির সাথে কার্য সম্পাদন/যোগাযোগ করার প্রাধিকার প্রাপ্ত ব্যক্তিদের নাম ও নমুনা স্বাক্ষরঃ",
"I/We hereby declare that all the information stated above and the documents attached with the application are true and correct to the best of my knowledge. We will be bound to accept the rules and regulations attached with the application form.We further agree that it shall be constructed as per the design of R.M.S and shall not make any changes thereto without the Company's permission.": "আমি/আমরা এই মর্মে ঘোষনা করিতেছি যে, উপরে বর্ণিত সকল তথ্য ও আবেদনপত্রের সহিত সংযুক্ত কাগজপত্রাদি আমার জানামতে সঠিক ও সত্য। আবেদনপত্রের সহিত সংযোজিত অংগীকার নামাসমূহ আমরা মানিয়া চলিতে বাধ্য থাকিব। আমরা আরও অংগীকার করিতেছি যে, আর এম.এস-এর ডিজাইন অনুসারে উহা নির্মাণ করা হইবে এবং উহাতে কোম্পানির অনুমতি ব্যতিরেকে কোন পরিবর্তন করিব না।",
"Name of Applicant:": "আবেদনকারীর নামঃ",
"Signature of Applicant:": "আবেদনকারীর সাক্ষরঃ",
"Designation:": "পদবীঃ",
"ID No:": "আইডি নঃ",
"Attachment: (✅)": "সংযুক্তিঃ(✅)",
"Bank Name:": "ব্যাংক এর নামঃ",
"Mobile Banking:": "মোবাইল ব্যাংকিংঃ",
"Necessary information (bank information, mobile banking number etc.)": "প্রয়োজনীয় তথ্য(ব্যাংক এর তথ্য, মোবাইল ব্যাংকিং নাম্বার ইত্যাদি।) ঃ"
}
